#define I_Dialog 256
#define I_Progress 257
#define I_Cancel 258
#define I_Back 259
#define I_Next 260
#define I_Icon 261
#define I_Logo 262
#define I_Status 263
#define I_Percent 264
#define I_Ja 265
#define I_Nein 266
#define I_Halt 267
#define I_Alle 268
#define I_Karte 269
#define I_Confirm 270
#define I_BMPWin 271
#define I_Dest 300
#define I_Text 301
#define I_OK 304
#define I_Cancel2 305

#define NONE 0
#define INSTALLING 1
#define ABORTED 2
#define COMPLETED 3

#define UPDATE_ALWAYS 1
#define UPDATE_NONEXIST 2

#define DLG_PACKAGESTOINSTALL 305
#define PACKAGES 306
#define PB_OK 313
#define PB_SELECTALL 308
#define PB_DESELECTALL 309
#define PB_CANCEL 314
#define DLG_SELECTINSTALLATIONDRIVE 311
#define DRIVELIST 312
